#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'apt', '~> 2.8.2'
cookbook 'java', '~> 1.31.0'
cookbook 'jenkins', '~> 2.4.1'
cookbook 'git', '~> 4.3.4'